version: "3.8"

services:
  web:
    build: .
    container_name: fastapi-ocr
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data: